// ALL ACTION TYPES

export const UPDATE_PERSONAL_DETAIL_TITLE = 'UPDATE_PERSONAL_DETAIL_TITLE'
export const UPDATE_JOB_TITLE = 'UPDATE_JOB_TITLE'
export const UDPATE_FIRST_NAME = 'UDPATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const UPDATE_CITY = 'UPDATE_CITY'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UDPATE_POSTAL_CODE = 'UDPATE_POSTAL_CODE'
export const UPDATE_DRIVING_LICENSE = 'UPDATE_DRIVING_LICENSE'
export const UPDATE_PLACE_OF_BIRTH = 'UPDATE_PLACE_OF_BIRTH'
export const UPDATE_DOB = 'UPDATE_DOB'
export const UDPATE_NATIONALITY = 'UDPATE_NATIONALITY'

export const UPDATE_PROFESSIONAL_DETAILS = 'UPDATE_PROFESSIONAL_DETAILS'
export const UPDATE_PROFESSIONAL_DETAILS_TITLE = 'UPDATE_PROFESSIONAL_DETAILS_TITLE'


export const UPDATE_EMPLOYMENT_HISTORY_TITLE = 'UPDATE_EMPLOYMENT_HISTORY_TITLE'
export const Add_NEW_EMPLYEEMENT_BOX = 'Add_NEW_EMPLYEEMENT_BOX'
export const DELETE_EMPLYEEMENT_BOX = 'DELETE_EMPLYEEMENT_BOX'
export const UPDATE_EMPLOYEE_HISTORY_JOB_TITLE = 'UPDATE_EMPLOYEE_HISTORY_JOB_TITLE'
export const UDPATE_EMPLOYER = 'UDPATE_EMPLOYER'
export const UPDATE_START_DATE = 'UPDATE_START_DATE'
export const UPDATE_END_DATE = 'UPDATE_END_DATE'


export const UPDATE_RESUME_TITLE = 'UPDATE_RESUME_TITLE'
export const UPDATE_RESUME_LANGUAGE = 'UPDATE_RESUME_LANGUAGE'

export const Add_NEW_EDUCATION_BOX = 'Add_NEW_EDUCATION_BOX'
export const DELETE_EDUCATION_BOX = 'DELETE_EDUCATION_BOX'
export const UPDATE_SCHOOL_COLLEGE = 'UPDATE_SCHOOL_COLLEGE'
export const UDPATE_DEGREE = 'UDPATE_DEGREE'
export const UPDATE_EDUCATION_START_DATE = 'UPDATE_EDUCATION_START_DATE'
export const UPDATE_EDUCATION_END_DATE = 'UPDATE_EDUCATION_END_DATE'
export const UPDATE_EDUCATION_CITY = 'UPDATE_EDUCATION_CITY'

export const Add_WEBSITE_LINK_BOX = 'Add_WEBSITE_LINK_BOX'
export const DELETE_WEBSITE_LINK_BOX = 'DELETE_WEBSITE_LINK_BOX'
export const UPDATE_LABEL = 'UPDATE_LABEL'
export const UDPATE_LINK = 'UDPATE_LINK'

