// ALL ACTION TYPES
export const UPDATE_JOB_TITLE = 'UPDATE_JOB_TITLE'
export const UDPATE_FIRST_NAME = 'UDPATE_FIRST_NAME'
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME'
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PHONE = 'UPDATE_PHONE'
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const UPDATE_CITY = 'UPDATE_CITY'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UDPATE_POSTAL_CODE = 'UDPATE_POSTAL_CODE'
export const UPDATE_DRIVING_LICENSE = 'UPDATE_DRIVING_LICENSE'
export const UPDATE_PLACE_OF_BIRTH = 'UPDATE_PLACE_OF_BIRTH'
export const UPDATE_DOB = 'UPDATE_DOB'
export const UDPATE_NATIONALITY = 'UDPATE_NATIONALITY'


export const UPDATE_RESUME_TITLE = 'UPDATE_RESUME_TITLE'
export const UPDATE_RESUME_LANGUAGE = 'UPDATE_RESUME_LANGUAGE'